name: moe-infinity
channels:
  - conda-forge
  - https://public.dhe.ibm.com/ibmdl/export/pub/software/server/ibm-ai/conda/
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - ca-certificates=2024.2.2=hbcca054_0
  - ld_impl_linux-64=2.38=h1181459_1
  - libffi=3.4.4=h6a678d5_0
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libstdcxx-ng=12.3.0=h0f45ef3_5
  - ncurses=6.4=h6a678d5_0
  - openssl=3.0.13=h7f8727e_0
  - pip=23.3.1=py39h06a4308_0
  - python=3.9.18=h955ad1f_0
  - readline=8.2=h5eee18b_0
  - setuptools=68.2.2=py39h06a4308_0
  - sqlite=3.41.2=h5eee18b_0
  - tk=8.6.12=h1ccaba5_0
  - wheel=0.41.2=py39h06a4308_0
  - xz=5.4.6=h5eee18b_0
  - zlib=1.2.13=h5eee18b_0
  - pip:
      - accelerate==0.27.2
      - aiohttp==3.9.3
      - aiosignal==1.3.1
      - alabaster==0.7.16
      - async-timeout==4.0.3
      - attrs==23.2.0
      - auto-gptq==0.7.0
      - babel==2.14.0
      - certifi==2024.2.2
      - chardet==5.2.0
      - charset-normalizer==3.3.2
      - coloredlogs==15.0.1
      - datasets==2.17.1
      - dill==0.3.8
      - docutils==0.20.1
      - filelock==3.13.1
      - frozenlist==1.4.1
      - fsspec==2023.10.0
      - gekko==1.0.6
      - hjson==3.1.0
      - huggingface-hub==0.21.1
      - humanfriendly==10.0
      - idna==3.6
      - imagesize==1.4.1
      - importlib-metadata==7.0.1
      - jinja2==3.1.3
      - markupsafe==2.1.5
      - moe-infinity==0.0.1.dev4
      - mpmath==1.3.0
      - multidict==6.0.5
      - multiprocess==0.70.16
      - networkx==3.2.1
      - ninja==1.11.1.1
      - numpy==1.26.4
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==8.9.2.26
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-nccl-cu12==2.19.3
      - nvidia-nvjitlink-cu12==12.3.101
      - nvidia-nvtx-cu12==12.1.105
      - optimum==1.17.1
      - packaging==23.2
      - pandas==2.2.1
      - peft==0.9.0
      - protobuf==4.25.3
      - psutil==5.9.8
      - py-cpuinfo==9.0.0
      - pyarrow==12.0.0
      - pyarrow-hotfix==0.6
      - pydantic==1.10.12
      - pygments==2.17.2
      - python-dateutil==2.8.2
      - pytz==2024.1
      - pyyaml==6.0.1
      - regex==2023.12.25
      - requests==2.31.0
      - rouge==1.0.1
      - safetensors==0.4.2
      - scipy==1.12.0
      - sentencepiece==0.2.0
      - six==1.16.0
      - snowballstemmer==2.2.0
      - sphinx==7.2.6
      - sphinxcontrib-applehelp==1.0.8
      - sphinxcontrib-devhelp==1.0.6
      - sphinxcontrib-htmlhelp==2.0.5
      - sphinxcontrib-jsmath==1.0.1
      - sphinxcontrib-qthelp==1.0.7
      - sphinxcontrib-serializinghtml==1.1.10
      - sympy==1.12
      - tokenizers==0.15.2
      - torch==2.2.1
      - tqdm==4.66.2
      - transformers==4.38.1
      - triton==2.2.0
      - typing-extensions==4.10.0
      - tzdata==2024.1
      - urllib3==2.2.1
      - xxhash==3.4.1
      - yarl==1.9.4
      - zipp==3.17.0
